### ISSUE TITLE
[Question] Are the two "wren" lang related?

### ISSUE THREAD

**Issue by grandsong** [wevrem/wren#2]
There is another "wren".

[Here is its GitHub repo](https://github.com/munificent/wren)

Both two langs seem to be in early phases and are actively maintained.

I guess it is just a coincidence that they are named the same.

However, I also noticed a lot of common shared in them.

Is there any relationship between the two?

---

The the same name will grow to a bigger and bigger problem that users have difficulty in distinguishing the two.

When talking about "wren" (such as on StackOverflow), people might waste a lot of time and thus their precise passion until they realize they are referring to different lanuguages.

And you can expect people post issues in wrong repos.

**Comment by wevre** [comment]
there is no relation to the two. This other appears to be older and, apparently, functioning. Mine is just an initial idea that I'm playing around with. I haven't even got the actual grammar working in Anltr yet. I'm not going to worry about name collisions yet until I see if mine even lifts off the ground.

**Comment by grandsong** [comment]
I see

**Comment by wevre** [comment]
I changed the name. I like three letter codes better and this name appears not to collide with anybody else's work out there, as far as I can tell.
