### ISSUE TITLE
[QUESTION] Custom rules

### ISSUE THREAD

**Issue by Skyost** [wevrem/wren#3]
Hey,

Your [Dent grammar file](https://github.com/wevrem/wry/blob/master/grammars/Dent.g4) is really cool ! I was just wondering how to add custom parser rules ?

For example if I want to add one of the following :

* `a <- expression` (assignment)
* `IF condition THEN` (if block)

I mean, I know how to add them in a traditionnal grammar file, but where should I put those rules in the Dent grammar file ?

Thanks for your reply !

EDIT :

Okay, my question may not be very clear. For example, if I want to add a print rule, in a standard file I do :

```antlr
statement
    : printStatement
    | ...
printStatement: 'PRINT' IDENTIFIER NEWLINE;

IDENTIFIER: [a-zA-Z0-9_]+;
```

My question is how can I add this to the already implemented `simpleStatement` rule ?

**Comment by wevre** [comment]
Hi,

You would probably replace. You don't have to adopt `simpleStatement` and `blockStatement`. Those, together with `LEGIT`, were just examples or placeholders. The crucial parts of Dent are `INDENT`, `DEDENT`, and `NEWLINE` and you can build whatever you want on top of them.

So, for example, `statement` and `LEGIT` could be replaced with something like the following:

```antlr
statement
    : printStatement
    | assignStatement
    | ifBlock
    | /* other statements */
    ;
printStatement : 'PRINT' IDENTIFIER NEWLINE;

ifBlock : 'IF' condition NEWLINE INDENT statement* DEDENT ;

/* flesh out other rules like `condition` and `assignStatement` */

IDENTIFIER: [a-zA-Z0-9_]+;
```

I hope that answers your question.

**Comment by Skyost** [comment]
Yep, you could not have answered better to my question. Thanks ! :wink:
