### ISSUE TITLE
Porting to C#?

### ISSUE THREAD

**Issue by mpelley** [wevrem/wren#4]
I'm using C# as the development language for an application.  I'd like to use your Dent since it seems like a straightforward approach to handling the indent method of identifying blocks for compound statements.  However, I was not able to port the Java code to C# because of two issues I ran into.  
1) The C# runtime does not have a `Token` class. 
2) The C# runtime has the `charPositionInLine` member `protected`.

Any suggestions for working around these issues?  Could I use the `CommonToken` class instead of `Token`?  I assume both implement IToken.

**Comment by wevre** [comment]
Dent isn't stand-alone Java, I'm not sure how you would port it to C# or really to anything. It's an ANTLR grammar file that gets turned into full-fledged Java code, with ANTLR providing the Token and CommonToken classes and a whole bunch of other stuff to make it work.

**Comment by wevre** [comment]
Let's try answering this again. I'm not familiar with the in's and out's of generating a C# parser with ANTLR, I've only worked on it with Java. It's even been long enough that I barely remember coming up with this code. Sorry I can't be more help other than the say, 'good luck!'
